name: Build app on PR
on:
 workflow_dispatch:
 pull_request:
  branches: [ dev ]


jobs:
 build:
  name: Build app
  runs-on: windows-2019
  steps:
   - uses: actions/checkout@v4
   - name: Setup NuGet
     uses: NuGet/setup-nuget@v2.0.0  
   - name: setup-msbuild
     uses: microsoft/setup-msbuild@v2
   - name: Restore Packages and build solution
     run: ".\\build.cmd nozip"
   - name: Upload a Build Artifact
     uses: actions/upload-artifact@v4.3.5
     with:
       # Artifact name
       name: pseudocode-ide
       # A file, directory or wildcard pattern that describes what to upload
       path: bin/Release/
 
