name: Build app on PR
on:
 workflow_dispatch:
 pull_request:
  branches: [ main, dev ]


jobs:
 build:
  name: Build app
  runs-on: windows-2019
  steps:
   - uses: actions/checkout@v2
   - name: Setup NuGet
     uses: NuGet/setup-nuget@v1.0.5  
   - name: setup-msbuild
     uses: microsoft/setup-msbuild@v1.1
   - name: Restore Packages and build solution
     run: ".\\build.cmd"
   - name: Upload a Build Artifact
     uses: actions/upload-artifact@v4.1.0
     with:
       # Artifact name
       name: pseudocode-ide
       # A file, directory or wildcard pattern that describes what to upload
       path: bin/Release/
 
