name: build app
on:
 workflow_dispatch:
 push:
  branches: [ main ]
 pull_request:
  branches: [ main ]


jobs:
 build:
  runs-on: windows-2019
  steps:
   - uses: actions/checkout@v2
   - name: Setup MSBuild
     uses: microsoft/setup-msbuild@v1
   - name: Setup NuGet
     uses: NuGet/setup-nuget@v1.0.5  
   - name: setup-msbuild
     uses: microsoft/setup-msbuild@v1.1
   - name: Restore Packages
     run: nuget restore pseudocodeIde.sln
   - name: Build solution
     run: msbuild pseudocodeIde.sln -t:rebuild -property:Configuration=Release
   - name: Upload a Build Artifact
     uses: actions/upload-artifact@v4.1.0
     with:
       # Artifact name
       name: pseudocode-ide
       # A file, directory or wildcard pattern that describes what to upload
       path: bin/Release/
 
