name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        semantic_version: 21
        tag_format: ${version}
        branches: |
          [
            'main',
            {
              name: 'dev',
              prerelease: true
            }
          ]
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
          semantic-release-replace-plugin
          
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}