name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Release
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5  
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        semantic_version: 21
        tag_format: ${version}
        branches: |
          [
            'main',
            {
              name: 'dev',
              prerelease: true
            }
          ]
        extra_plugins: |
          @semantic-release/changelog@6.0.3
          @semantic-release/git@10.0.1
          @saithodev/semantic-release-backmerge@4.0.1
          semantic-release-replace-plugin@1.2.7
          @semantic-release/exec@6.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}